<template>
  <component :is="iconType" />
</template>
<script lang="ts">
// 公共页面不要修改 如果达不到你的要求 找zhangle 让他来改
import { defineComponent, ref } from "vue";
import {
  LockOutlined,
  PlusOutlined,
  SearchOutlined,
  EyeOutlined,
  EditOutlined,
  SendOutlined,
  BlockOutlined,
  PrinterOutlined,
  ExportOutlined,
  DeleteOutlined,
  FastBackwardOutlined,
  FlagOutlined,
  DownloadOutlined,
  UploadOutlined,
  ArrowUpOutlined,
  ArrowDownOutlined,
  ArrowLeftOutlined,
  ArrowRightOutlined,
  SnippetsOutlined,
  DiffOutlined,
  OrderedListOutlined,
  SaveOutlined,
  SecurityScanOutlined,
  MenuFoldOutlined,
  MenuUnfoldOutlined,
  PieChartOutlined,
  MailOutlined,
  DesktopOutlined,
  InboxOutlined,
  AppstoreOutlined,
  CalendarOutlined,
  SettingOutlined,
  UserOutlined,
  TeamOutlined,
  SolutionOutlined,
  ShoppingCartOutlined,
  SyncOutlined,
  FunnelPlotOutlined,
  BankOutlined,
  AccountBookOutlined,
  AppstoreAddOutlined,
  SmileOutlined,
  ContactsOutlined,
  UndoOutlined,
  HomeOutlined,
  FormOutlined,
  DotChartOutlined
} from "@ant-design/icons-vue";
export default defineComponent({
  name: "ICONCOM",
  components: {
    LockOutlined,
    PlusOutlined,
    SearchOutlined,
    EyeOutlined,
    EditOutlined,
    SendOutlined,
    BlockOutlined,
    PrinterOutlined,
    DeleteOutlined,
    FastBackwardOutlined,
    FlagOutlined,
    DownloadOutlined,
    UploadOutlined,
    ArrowUpOutlined,
    ArrowDownOutlined,
    ArrowLeftOutlined,
    ArrowRightOutlined,
    SnippetsOutlined,
    DiffOutlined,
    OrderedListOutlined,
    SaveOutlined,
    SecurityScanOutlined,
    MenuFoldOutlined,
    MenuUnfoldOutlined,
    PieChartOutlined,
    MailOutlined,
    DesktopOutlined,
    ExportOutlined,
    InboxOutlined,
    AppstoreOutlined,
    CalendarOutlined,
    SettingOutlined,
    UserOutlined,
    TeamOutlined,
    SolutionOutlined,
    ShoppingCartOutlined,
    SyncOutlined,
    FunnelPlotOutlined,
    BankOutlined,
    AccountBookOutlined,
    AppstoreAddOutlined,
    SmileOutlined,
    ContactsOutlined,
    UndoOutlined,
    HomeOutlined,
    FormOutlined,
    DotChartOutlined,
  },
  props: {
    type:{
      required: true,
    }
  },
  setup(props, ctx) {
    const iconType = ref(props.type);
    return {
      iconType,
    };
  },
});
</script>
